// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qphdzdgqetwszuscfwld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwaGR6ZGdxZXR3c3p1c2Nmd2xkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5ODMyNDcsImV4cCI6MjA2MTU1OTI0N30.7r4tl4XWuBoa4slTHneQt1kcGVetZCR9K25L3Eyp9zM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);